drop table if exists public.authors;
drop type if exists public.gender;
CREATE TYPE gender as enum(
'MALE',
    'FEMALE'
);
create table public.authors(
                               id BIGINT unique not null primary key
                                   GENERATED BY DEFAULT AS IDENTITY,
                               name varchar(60)not null ,
                               last_name varchar(50)not null ,
                               date_of_birth timestamp not null ,
                               country varchar(50) not null ,
                               gender gender not null

);
