drop table if exists genres;
create table public.genres
(
    id             BIGINT       not null unique primary key
        GENERATED BY DEFAULT As identity,
    name           varchar(50)  not null,
    description    VARCHAR(100) not null,
    year_of_origin INTEGER      not null
);
