drop table if exists purchases;
create table public.purchases(
    id BIGINT not null unique primary key
                            generated by default as identity,
                            name varchar (30)not null,
                            buyer_name varchar (30) not null ,
                            last_name varchar (30) not null ,
                            country varchar (30)not null ,
                            region varchar (30)not null ,
                            locality varchar (30)not null ,
                            zip_code INTEGER  not null
);